# Generated by Django 2.0.7 on 2018-08-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('source', models.FileField(upload_to='uploads/')),
                ('type', models.CharField(choices=[('I', 'Image'), ('V', 'Video')], max_length=2)),
                ('start_date', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('end_date', models.DateTimeField()),
                ('duration', models.IntegerField(default=10)),
            ],
        ),
    ]
