# Generated by Django 2.0.7 on 2018-08-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='duration',
            field=models.IntegerField(default=15),
        ),
    ]
